### ISSUE TITLE
Doing More than Only Turn on and OFF TV

### ISSUE THREAD

**Issue by rajdpandey** [nugoo1/Alexa-IR-Remote#2]
Hi,

I want to do more than just turning ON or OFF the TV. After turning ON TV when I say "Alexa Increase the TV volume" or "Alexa, mute the tv" etc it should also work for that.

So how can I implement these?

**Comment by nugoo1** [comment]
You need to record the specific IR code emitted from your remote for volume up or down and then configure that code to fire through your NodeMCU when you ask alexa to do so..

**Comment by nugoo1** [comment]
You need to record the specific IR code emitted from your remote for volume up or down and then configure that code to fire through your NodeMCU when you ask alexa to do so..

**Comment by rajdpandey** [comment]
Hi, 

Can you please say if this is correct for the Increasing and decreasing volume and for mute?
lightOne = new Switch("TV", 3611, lightOneOn, lightOneOff);
lightTwo = new Switch("HDMI", 3612, lightTwoOn, lightTwoOff);
lightThree = newSwitch("VOLUME",3613,IncreaseVol,DecreaseVol)
lightFour = newSwitch("MUTE",3614,MuteVol,UnmuteVol)


Is this right for Increase Volume of TV, Decreasing Volume and making it Mute? 
Please provide your insights...
If above is right then I can do rest of sending code function and all.

**Comment by nugoo1** [comment]
Yeah pretty much.. What u call it doesnt matter much, I don't understand why you are spending time even thinking about it.. Its just a variable asigned to the IR code

**Comment by nugoo1** [comment]
Yes correct, doesnt matter what u call it. Just initialize callbacks etc., same as other switches.

**Comment by rajdpandey** [comment]
If possible can you try it so you will also have some insight and you will know better how to tweak if it goes south?

**Comment by nugoo1** [comment]
It's a simple piece of code, just experiment! I might do a youtube video, don't be so scared of failing lol

**Comment by rajdpandey** [comment]
OK, I will do it. Thanks for help.  when you complete it Please Share your youtube link.
